name: chat_sample_app
description: "Websocket chat sample app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  ansicolor: ^2.0.1
  socket_io: ^1.0.1
  socket_io_client: 1.0.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  auto_route: ^9.2.2
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  injectable: ^2.4.1
  get_it: ^8.0.1
  retrofit: ^4.1.0
  dio: ^5.4.2+1
  loggy: ^2.0.3
  flutter_loggy: ^2.0.3
  bloc_concurrency: ^0.2.5
  collection: ^1.18.0
  dartz: ^0.10.1
  rxdart: ^0.28.0
  shared_preferences: ^2.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  auto_route_generator: ^9.0.0
  flutter_gen_runner: ^5.8.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.4
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/